In [5]:
import pandas as pd

df = pd.read_csv(r"C:\Users\karan\OneDrive\Desktop\project\Sample - Superstore.csv", encoding='latin1')

df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,262.0,2,0.00,41.9
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9,3,0.00,219.6
2,3,CA-2016-138688,12-06-2016,6-16-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6,2,0.00,6.9
3,4,US-2015-108966,11-10-2015,10-18-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.6,5,0.45,-383.0
4,5,US-2015-108966,11-10-2015,10-18-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.4,2,0.20,2.5
5,6,CA-2014-115812,09-06-2014,6-14-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.9,7,0.00,14.2
6,7,CA-2014-115812,09-06-2014,6-14-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.3,4,0.00,2.0
7,8,CA-2014-115812,09-06-2014,6-14-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.2,6,0.20,90.7
8,9,CA-2014-115812,09-06-2014,6-14-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5,3,0.20,5.8
9,10,CA-2014-115812,09-06-2014,6-14-2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9,5,0.00,34.5

In [6]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [8]:
# Converting Order dates and Ship dates into date fromat 

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [10]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [13]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   int64
 1   order_id       9994 non-null   object
 2   order_date     9994 non-null   datetime64[ns]
 3   ship_date      9994 non-null   datetime64[ns]
 4   ship_mode      9994 non-null   object
 5   customer_id    9994 non-null   object
 6   customer_name  9994 non-null   object
 7   segment        9994 non-null   object
 8   country        9994 non-null   object
 9   city           9994 non-null   object
 10  state          9994 non-null   object
 11  postal_code    9994 non-null   int64
 12  region         9994 non-null   object
 13  product_id     9994 non-null   object
 14  category       9994 non-null   object
 15  sub-category   9994 non-null   object
 16  product_name   9994 non-null   object
 17  sales          9994 non-null   float64
 18  quantity       9994 non-null   int64
 19  discount       9994 non-null   float64
 20  profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   int64
 1   order_id       9994 non-null   object
 2   order_date     9994 non-null   datetime64[ns]
 3   ship_date      9994 non-null   datetime64[ns]
 4   ship_mode      9994 non-null   object
 5   customer_id    9994 non-null   object
 6   customer_name  9994 non-null   object
 7   segment        9994 non-null   object
 8   country        9994 non-null   object
 9   city           9994 non-null   object
 10  state          9994 non-null   object
 11  postal_code    9994 non-null   int64
 12  region         9994 non-null   object
 13  product_id     9994 non-null   object
 14  category       9994 non-null   object
 15  sub-category   9994 non-null   object
 16  product_name   9994 non-null   object
 17  sales          9994 non-null   float64
 18  quantity       9994 non-null   int64
 19  discount       9994 non-null   float64
 20  profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [16]:
df.groupby('region')['sales'].sum()

region
Central    501251.3
East       678797.1
South      391731.2
West       725478.4
Name: sales, dtype: float64

In [17]:
df.groupby('category')['profit'].sum().sort_values(ascending=False)

category
Technology         145462.5
Office Supplies    122492.8
Furniture           18453.7
Name: profit, dtype: float64

In [18]:
df.groupby('sub-category')['sales'].sum().sort_values(ascending=False)

sub-category
Phones         330020.0
Chairs         328453.0
Storage        223846.6
Tables         206967.4
Binders        203416.8
Machines       189239.6
Accessories    167389.2
Copiers        149529.5
Bookcases      114882.4
Appliances     107533.0
Furnishings     91709.9
Paper           78485.2
Supplies        46674.2
Art             27120.8
Envelopes       16478.0
Labels          12487.6
Fasteners        3024.8
Name: sales, dtype: float64

In [19]:
df.groupby('customer_id')['sales'].sum().sort_values(ascending=False).head(3).tail(2)

customer_id
TC-20980    19052.3
RB-19360    15117.3
Name: sales, dtype: float64

In [20]:
top_customer = (
    df.groupby(['region','customer_name'])['sales']
    .sum()
    .reset_index()
    .sort_values(['region','sales'], ascending=[True, False])
    .groupby('region')
    .head(1)
)

In [21]:
top_customer

       region customer_name    sales
579   Central  Tamara Chand  18437.3
1276     East  Tom Ashbrook  13723.5
1745    South   Sean Miller  23669.3
2354     West  Raymond Buch  14345.3

In [22]:
loss_products = df[df['profit'] < 0]
loss_products[['product_name','sales','profit']].head(10)

                                         product_name   sales  profit
3       Bretford CR4500 Series Slim Rectangular Table   957.6  -383.0
14  Holmes Replacement Filter for HEPA Air Cleaner...    68.8  -123.9
15   Storex DuraTech Recycled Plastic Frosted Binders     2.5    -3.8
23                 Global Deluxe Stacking Chair, Gray    71.4    -1.0
27  Riverside Palais Royal Lawyers Bookcase, Royal...  3083.4 -1665.1
28  Avery Recycled Flexi-View Covers for Binding S...     9.6    -7.1
32  Acco Pressboard Covers with Storage Hooks, 14 ...     6.9    -5.7
36  Electrix Architect's Clamp-On Swing Arm Lamp, ...   190.9  -148.0
38  Atlantic Metals Mobile 3-Shelf Bookcases, Cust...   532.4   -47.0
39           Global Fabric Manager's Chair, Dark Gray   212.1   -15.1

In [23]:
df.groupby('discount')['profit'].mean().sort_index()

discount
0.00     66.902355
0.10     96.053191
0.15     27.290385
0.20     24.703309
0.30    -45.679736
0.32    -88.566667
0.40   -111.926214
0.45   -226.636364
0.50   -310.703030
0.60    -43.078261
0.70    -95.874880
0.80   -101.797667
Name: profit, dtype: float64

In [24]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\karan\appdata\local\programs\python\python313\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\karan\appdata\local\programs\python\python313\lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in c:\users\karan\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\karan\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
from sqlalchemy import create_engine

In [26]:
!pip install cryptography

Requirement already satisfied: cryptography in c:\users\karan\appdata\local\programs\python\python313\lib\site-packages (46.0.5)
Requirement already satisfied: cffi>=2.0.0 in c:\users\karan\appdata\local\programs\python\python313\lib\site-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in c:\users\karan\appdata\local\programs\python\python313\lib\site-packages (from cffi>=2.0.0->cryptography) (2.23)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
username = "root"
password = "Kaikira820"
host = "localhost"
port = "3306"
database = "superstore" 

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

table_name = 'Superstore_sales'
df.to_sql(table_name,engine,if_exists="replace",index = False)

C:\Users\karan\AppData\Local\Temp\ipykernel_16584\372766141.py:10: UserWarning: The provided table name 'Superstore_sales' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(table_name,engine,if_exists="replace",index = False)

9994